spring:
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL
    username: sa
    password:

masterapp:
  infolder: classpath:input/*.xml
  inroot: company

logging:
  path: log/master
  level:
    root: info
    com:
      arrobaautowired: debug
    org:
      springframework:
        batch: trace
        oxm: trace
        integration: info

master:
  broker-url: tcp://localhost:61616