spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL

masterapp:
  infolder: classpath:input/
  inroot: company

logging:
  level:
    root: info
    com:
      arrobaautowired: debug
    org:
      springframework:
        batch: trace
        oxm: trace
        integration: trace